config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: "registrations"
  }
  resources :exames, only: [:index, :show, :new, :create, :edit, :update]
  resources :users, only: [:show, :edit, :update]
  
  root "exames#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exame.rb
class Exame < ApplicationRecord
  belongs_to :doctor, class_name: "User"
  belongs_to :patient, class_name: "User"

  validates :title, presence: true
  validates :description, presence: true
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :user_hospitals
  has_many :users, through: :user_hospitals, class_name: 'User'
  has_many :exames

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_validation :normalize_phone_number, on: :create

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :user_hospitals
  has_many :hospitals, through: :user_hospitals, class_name: 'Hospital'
  has_many :doctor_exames, class_name: 'Exame', foreign_key: 'doctor_id'
  has_many :patient_exames, class_name: 'Exame', foreign_key: 'patient_id'

  validates :name, presence: true
  validates :email, presence: true
  validates :phone_number, presence: true

  accepts_nested_attributes_for :user_hospitals

  def self.doctors
    joins(:user_hospitals).where(user_hospitals: { role: 'doctor' })
  end

  def self.patients
    joins(:user_hospitals).where(user_hospitals: { role: 'patient' })
  end

  def normalize_phone_number
    self.phone_number = PhoneNormalizerService.normalize(phone_number)
  end

  def doctor?
    user_hospitals.exists?(role: 'doctor')
  end

  def patient?
    user_hospitals.exists?(role: 'patient')
  end

  def exames
    Exame.where('doctor_id = ? OR patient_id = ?', id, id)
  end

  def doctor_exames
    Exame.joins(:doctor).where(doctor: { id: id })
  end

  def patient_exames
    Exame.joins(:patient).where(patient: { id: id })
  end
end

app/models/user_hospital.rb
class UserHospital < ApplicationRecord
  belongs_to :user
  belongs_to :hospital
  enum role: { doctor: 0, patient: 1}

  validates :role, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exames_controller.rb
class ExamesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_exame, only: [:show, :edit, :update]
  before_action :check_doctor_permission, only: [:new, :create, :edit, :update]

  def index
    @exames = current_user.doctor? ? current_user.doctor_exames : current_user.patient_exames
  end

  def show
  end

  def new
    @exame = Exame.new
    @patients = User.patients.order(:name)
  end

  def create
    @exame = current_user.doctor_exames.new(exame_params)
    if @exame.save
      redirect_to exame_path(@exame), notice: 'Exame criado com sucesso.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @exame.update(exame_params)
      redirect_to exame_path(@exame), notice: 'Exame atualizado com sucesso.'
    else
      render :edit
    end
  end

  private

  def set_exame
    @exame = Exame.find(params[:id])
  end

  def exame_params
    params.require(:exame).permit(:title,:description, :doctor_id, :patient_id)
  end

  def check_doctor_permission
    unless current_user.doctor?
      redirect_to root_path, alert: 'Acesso negado. Somente médicos podem realizar essa ação.'
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, only: [:create]

  def new
    super do |resource|
      resource.user_hospitals.build
    end
  end 

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number, user_hospitals_attributes: [:role, :hospital_id]])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
  
    if @user.save!
      redirect_to user_path(@user), notice: "User was successfully created."
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "User was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: "User was successfully destroyed."
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :phone_number, user_hospitals_attributes: [:role, :hospital_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def doctor?
    current_user&.doctor?
  end

  def navbar_links
    link_to "Exames", exames_path, class: "nav-link" if current_user.present?
  end
end

app/views/exames/edit.html.erb
<div class="container">
  <h1>Editar Exame</h1>

  <%= form_with model: @exame, url: exame_path(@exame), method: :patch do |form| %>
    <div class="mb-3">
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :doctor_id, class: "form-label" %>
      <%= form.collection_select :doctor_id, User.doctors, :id, :name, { include_blank: true }, { class: "form-select", disabled: true } %>
    </div>

    <div class="mb-3">
      <%= form.label :patient_id, class: "form-label" %>
      <%= form.collection_select :patient_id, User.patients, :id, :name, { include_blank: true }, { class: "form-select", disabled: true } %>
    </div>

    <div class="text-end">
      <%= form.submit "Salvar", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/exames/index.html.erb
<div class="container">
  <h1 class="text-center mt-5 mb-4">Lista de Exames</h1>

  <div class="row">
    <% @exames.each do |exame| %>
      <div class="col-md-4">
        <div class="card mb-3">
          <div class="card-body text-center">
            <h5 class="card-title mb-3"><%= exame.title %></h5>
            <p class="card-text"><strong>Médico:</strong> <%= exame.doctor.name %></p>
            <p class="card-text"><strong>Paciente:</strong> <%= exame.patient.name %></p>
            <%= link_to 'Ver Detalhes', exame_path(exame), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

 <% if doctor? %>
  <div class="text-center">
    <%= link_to 'Cadastrar Novo Exame', new_exame_path, class: 'btn btn-success' %>
  </div>
<% end %>
</div>

app/views/exames/new.html.erb
<div class="container">
  <h1>Cadastrar Novo Exame</h1>

  <%= form_with model: @exame, url: exames_path do |form| %>
    <div class="mb-3">
      <%= form.label :title, 'Título' %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :description, 'Descrição' %>
      <%= form.text_area :description, class: 'form-control' %>
    </div>

    <% if doctor? %>
      <%= form.hidden_field :doctor_id, value: current_user.id %>
    <% end %>

    <div class="mb-3">
      <%= form.label :patient_id, 'Paciente' %>
      <%= form.collection_select :patient_id, @patients, :id, :name, { include_blank: true }, { class: 'form-select' } %>
    </div>

    <div class="text-end">
      <%= form.submit 'Salvar', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/exames/show.html.erb
<div class="container">
  <h1>Detalhes do Exame</h1>

  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Título</h5>
      <p class="card-text"><%= @exame.title %></p>
      <h5 class="card-title">Descrição</h5>
      <p class="card-text"><%= @exame.description %></p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><strong>Médico:</strong> <%= @exame.doctor.name %></li>
      <li class="list-group-item"><strong>Paciente:</strong> <%= @exame.patient.name %></li>
    </ul>
  </div>

  <% if doctor? %>
    <%= link_to 'Editar Exame', edit_exame_path(@exame), class: "btn btn-primary mt-3" %>
  <% end %>

  <%= link_to 'Voltar', exames_path, class: "btn btn-primary mt-3" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LabPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
      <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="bg-light text-center text-lg-start fixed-bottom">
  <div class="container p-4">
    <div class="row">
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
        <h5 class="text-uppercase">LabPortal</h5>
        <p>LabPortal é uma Plataforma criada pela <a href="https://almosthackers.net/">AlmostHackers</a>.</p>
      </div>
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase">Contact</h5>
        <ul class="list-unstyled">
          <li>Phone: +55 123-456-789</li>
          <li>Email: info@labportal.com</li>
          <li>Address: Rio de Janeiro, Brasil</li>
        </ul>
      </div>
    </div>
  </div>

  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    &copy; <%= Time.now.year %> LabPortal. All rights reserved.
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "LabPortal", root_path, class: "navbar-brand" %>
  
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <%= link_to "Exames", exames_path, class: "nav-link" %>
        </li>
      </ul>
      <% if current_user.present? %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Meus Dados", user_path(current_user), class: "nav-link" %>
          </li>
        </ul>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/users/show.html.erb
<div class="container">
  <h1>Meus Dados</h1>

  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Nome: <%= current_user.name %></h5>
      <p class="card-text">Email: <%= current_user.email %></p>
      <p class="card-text">Telefone: <%= current_user.phone_number %></p>
      <!-- Adicione mais campos do usuário conforme necessário -->

      <%= link_to "Editar Dados", edit_user_registration_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>